apiVersion: cert-manager.io/v1alpha2
kind: Issuer 
metadata:
  name: 'letsencrypt-apinatomy'
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: filippo@metacell.us
    privateKeySecretRef:
      name: letsencrypt-apinatomy
    solvers:
    - http01:
        ingress:
          ingressName: apinatomy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-apinatomy
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
  name: apinatomy
spec:
  rules:
  - host: "{{DOMAIN}}"
    http:
      paths:
      - backend:
          service:
            name: apinatomy
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - "{{DOMAIN}}"
    secretName: apinatomy-tls
