name: Tests Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the specified branch
  push:
    branches:
     - "master"
     - "develop"
  pull_request:
    branches:
     - "master"
     - "develop"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    container: lironavon/docker-puppeteer-container:14.16.0
    env:
      CI: true
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: ${{ matrix.node-version }}
    - name: scaffold elements snapshot test
      run: |
          #install dependencies
          npm ci
          # run scaffold element snapshot tests
          npm run snapshot_test
      env:
          CI: true
