# This is a basic workflow to help you get started with Actions

name: Test CI
on:
  push:
    branches: [ tests/164 ]
  pull_request:
    branches: [ tests/164 ]
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 24
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm snapshot_test
